# Generated by Django 5.0 on 2023-12-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=15)),
                ('move_1', models.CharField(max_length=15)),
                ('move_2', models.CharField(max_length=15)),
                ('front_img', models.URLField()),
                ('back_img', models.URLField()),
                ('hp', models.IntegerField(default=10)),
                ('xp', models.IntegerField(default=0)),
            ],
        ),
    ]
