# Generated by Django 5.0 on 2023-12-30 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=15)),
                ('move_1', models.CharField(max_length=15)),
                ('move_2', models.CharField(max_length=15)),
                ('front_img', models.URLField()),
                ('back_img', models.URLField()),
                ('pokemon_id', models.IntegerField()),
                ('hp', models.IntegerField(default=10)),
                ('xp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_pokemon', to='pokemon_app.pokemon')),
            ],
        ),
    ]
