# Generated by Django 5.0 on 2024-01-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='base_hp',
            field=models.IntegerField(default=10),
        ),
    ]
