# Generated by Django 5.0 on 2024-01-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('is_selected', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Pokemon Team', max_length=255)),
                ('pokemons', models.ManyToManyField(related_name='teams', to='pokemon_app.userpokemon')),
            ],
        ),
    ]
