# Generated by Django 5.0 on 2023-12-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='back_img',
        ),
        migrations.RemoveField(
            model_name='team',
            name='front_img',
        ),
        migrations.RemoveField(
            model_name='team',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='team',
            name='move_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='move_2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='type',
        ),
        migrations.RemoveField(
            model_name='team',
            name='xp',
        ),
    ]
