
# Generated by Django 5.0 on 2023-12-30 20:30


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon_app', '0002_initial'),
        ('team_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teampokemon',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_app.team'),
        ),
        migrations.AddField(
            model_name='teampokemon',
            name='user_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_pokemon', to='pokemon_app.userpokemon'),
        ),
        migrations.AlterUniqueTogether(
            name='teampokemon',
            unique_together={('team', 'user_pokemon')},
        ),
    ]
