# Generated by Django 5.0 on 2023-12-27 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
        ('team_app', '0002_remove_team_back_img_remove_team_front_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_pokemon', to='team_app.team')),
            ],
        ),
    ]
