# Generated by Django 5.0 on 2023-12-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0002_initial'),
        ('team_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pokemons',
            field=models.ManyToManyField(related_name='teams', to='pokemon_app.userpokemon'),
        ),
    ]
